version: "3.9"
services:
  userserver:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    restart: always
    container_name: "user-server"
    ports:
      - 5000:80
    environment:
      - USER_PORT=5000
      - USER_MONGO_DB_URI=mongodb://root:pass@mongo:27017
    depends_on:
      mongo:
        condition: service_healthy

  accommodationserver:
    build:
      context: .
      dockerfile: AccommodationService/Dockerfile
    restart: always
    container_name: "accommodation-server"
    ports:
      - 5001:80
    environment:
      - ACCOMMODATION_PORT=5001
      - ACCOMMODATION_MONGO_DB_URI=mongodb://root:pass@mongo:27017
    depends_on:
      mongo:
        condition: service_healthy     

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydatabase
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      # hostname of mongo database
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    volumes:
      - mongo_express_data:/data/db

volumes:
  mongo_store:
  mongo_express_data: